version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-vmlc-vscode-java-dev

    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
    ide-type: vscode

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - code --install-extension vscjava.vscode-java-pack
      - code --install-extension pivotal.vscode-boot-dev-pack

  kube-deploy-files: "idea-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "idea-vmlc-docker-compose.yaml"
